devsearch3/devsearch1/devsearch1/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
       
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT )

devsearch3/devsearch1/users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.profiles, name="profiles"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),

]

devsearch3/devsearch1/projects/models.py
from django.db import models
import uuid
from users.models import Profile

class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length = 200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank =True, default="default.jpg") 
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank= True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total= models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title


class Review(models.Model):
    VOTE_TYPE = (
        ('up','Up vote'),
        ('down','Down Vote'),
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null= True, blank=True)
    value = models.CharField(max_length = 200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default = uuid.uuid4, unique = True, primary_key=True, editable = False)

    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200 )
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default = uuid.uuid4, unique = True, primary_key=True, editable = False)

    def __str__(self):
        return self.name

        

devsearch3/devsearch1/users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid 

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null =True, blank=True)
    name = models.CharField(max_length =200, blank=True, null =True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length = 200, blank=True, null=True)
    location = models.CharField(max_length = 200, blank=True, null=True)
    short_intro = models.CharField(max_length =200, blank=True, null =True)
    bio = models.TextField(blank=True, null =True)
    profile_image = models.ImageField(null=True, blank =True, upload_to='profiles/', default = "profiles/user-default.png")

    social_github = models.CharField(max_length =200, blank=True, null =True)
    social_twitter = models.CharField(max_length =200, blank=True, null =True)
    social_linkedin = models.CharField(max_length =200, blank=True, null =True)
    social_youtube= models.CharField(max_length =200, blank=True, null =True)
    social_website = models.CharField(max_length =200, blank=True, null =True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)


    def __str__(self):
        return str(self.user.username)


class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete= models.CASCADE, null=True, blank=True)

    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)


    def __str__(self):
        return str(self.name)
    

devsearch3/devsearch1/users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Skill, Message


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name': 'Name',
        }

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'email', 'username',
                  'location', 'bio', 'short_intro', 'profile_image',
                  'social_github', 'social_linkedin', 'social_twitter',
                  'social_youtube', 'social_website']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = '__all__'
        exclude = ['owner']

    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

devsearch3/devsearch1/users/views.py
from django.shortcuts import render
from .models import Profile
# Create your views here.


def profiles(request):
    profiles = Profile.objects.all()
    context = {'profiles':profiles}
    return render(request, 'users/profiles.html', context)
     

def userProfile(request, pk):
    profile = Profile.objects.get(id =pk)
    context ={'profile':profile}
    return render(request, 'users/user-profile.html', context)

    

devsearch3/devsearch1/users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}
<main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">

            {% for profile in profiles %}
          <div class="column card">
            <div class="dev">
              <a href="{% url 'user-profile' profile.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{ profile.profile_image.url }}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{profile.name}}</h3>
                    <h5>{{profile.short_intro}}</h5>
                  </div>
                </div>
                <p class="dev__info">{{profile.bio|slice:"60"}}</p>
                <div class="dev__skills">

                    {%  for skill in profile.skill_set.all %}
                  <span class="tag tag--pill tag--main">
                    <small>{{skill}}</small>
                  </span>
                  {% endfor %}
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>

    
</main>
{% endblock %}

devsearch3/devsearch1/users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}

<main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="https://avatars.githubusercontent.com/u/33843378" />
              <h2 class="dev__name">{{profile.name}}}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">Based in {{profile.location}}</p>
              <ul class="dev__social">
                <li>
                  <a title="Github" href="#" target="_blank"><i class="im im-github"></i></a>
                </li>
                <li>
                  <a title="Stackoverflow" href="#" target="_blank"><i class="im im-stackoverflow"></i></a>
                </li>
                <li>
                  <a title="Twitter" href="#" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                <li>
                  <a title="LinkedIn" href="#" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                <li>
                  <a title="Personal Website" href="#" target="_blank"><i class="im im-globe"></i></a>
                </li>
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ex illum ipsum iusto consequatur. Totam,
              dolorum fugiat, debitis facere illo nostrum nesciunt maxime, deserunt enim voluptatibus modi natus velit
              voluptatum. Dicta eritatis exercitationem ut quos a placeat obcaecati? Architecto illum!
              <br />
              Amet consectetur adipisicing elit. Veritatis exercitationem ut quos a placeat obcaecati? Architecto
              illum, atque delectus nemo dolorem inventore ab facilis? Dolor placeat vel delectus ipsam ullam.
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
              <div class="devSkill">
                <h4 class="devSkill__title">JavaScript</h4>
                <p class="devSkill__info">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae neque voluptatum ut? Quaerat, ea
                  cumque! Dolorum provident esse molestias commodi odit sapiente quod quasi corrupti obcaecati? Nobis
                  ex temporibus quaerat!
                </p>
              </div>
              <div class="devSkill">
                <h4 class="devSkill__title">React</h4>
                <p class="devSkill__info">
                  Smet consectetur adipisicing elit. Omnis, nihil? Accusamus aspernatur aut debitis vitae quaerat
                  nihil fugiat, doloremque nesciunt alias pariatur maxime unde, nam saepe laborum at odit labore.
                </p>
              </div>
              <div class="devSkill">
                <h4 class="devSkill__title">Express(Nodejs)</h4>
                <p class="devSkill__info">
                  Auae error deleniti aperiam enim nisi nesciunt, ratione eveniet eos fuga ad recusandae mollitia!
                  Facere earum, distinctio nihil recusandae ipsum nesciunt. Possimus, ex. Officia maxime nihil
                  inventore cum tenetur! Veritatis sapiente libero ducimus nesciunt itaque, placeat inventore sint
                  blanditiis?
                </p>
              </div>

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>Figma</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>Vuejs</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>REST API</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>GraphQL</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>TypeScript</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>Webpack</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>NextJS</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>Postgres</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>MongoDB</small>
                </span>
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

                {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{project.featured_image.url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      <p><a class="project__author" href ="profile.html">By {{project.owner.name}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Positive Feedback({{project.vote_total|pluralize:"s"}} Votes)
                      </p>
                      <div class="project__tags">
                        {% for tag in project.tag.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                        {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>

              

             
           
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endfor %}
{% endblock content %}